import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>React Query Talk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <Link
            href="/redux/1"
            className={styles.card}
          >
            <h2>
              Redux <span>-&gt;</span>
            </h2>
            <p>
              Current implementation @ Kogan.com
            </p>
          </Link>

          <Link
            href="/query/1"
            className={styles.card}
          >
            <h2>
              React Query <span>-&gt;</span>
            </h2>
            <p>
              What it could be!
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
